# Generated by Django 3.2.12 on 2022-03-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_manage_book', 'Create, Update and Delete Book'),)},
        ),
    ]
